version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:basic-amd64
    container_name: crawl4ai
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_CONCURRENT_TASKS=2
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          memory: 50G
    restart: unless-stopped
